volumes:
  clickhouse_data: {}

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
      - "9009:9009"   # Interserver communication port
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=ClickHousePassword
      - CLICKHOUSE_DB=default

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    container_name: clickhouse-client
    entrypoint: /bin/sleep
    command: infinity
    environment:
      - CLICKHOUSE_HOST=clickhouse-server
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=ClickHousePassword
    depends_on:
      - clickhouse-server