volumes:
  clickhouse_data: {}
  clickhouse_logs: {}

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.4
    container_name: clickhouse-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse_config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse_config/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
      - "9009:9009"   # Interserver communication port
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=ClickHousePassword
      - CLICKHOUSE_DB=default