{
 "title": "Flight Data by Time",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Receiver",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Average Horizontal Distance to Aircraft",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT TIME_FLOOR(\"__time\",'PT2M') AS \"__time\", \"client_id\", AVG(CAST(\"distance_to_aircraft\" AS DOUBLE)) AS \"distance_to_aircraft\" FROM \"adsb-json\" WHERE  \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"client_id\" IN (${Receiver:sqlstring}) AND \"distance_to_aircraft\" IS NOT NULL GROUP BY 1, 2",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT TIME_FLOOR(\\\"__time\\\",'PT2M') AS \\\"__time\\\", \\\"client_id\\\", AVG(CAST(\\\"distance_to_aircraft\\\" AS DOUBLE)) AS \\\"distance_to_aircraft\\\" FROM \\\"adsb-json\\\" WHERE  \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"client_id\\\" IN (${Receiver:sqlstring}) AND \\\"distance_to_aircraft\\\" IS NOT NULL GROUP BY 1, 2\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Aircraft Tracked by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n  TIME_EXTRACT(\"__time\",'hour') AS \"hour\",\n  COUNT (DISTINCT \"hex_ident_val\") AS \"aircraft tracked\",\n  \"client_id\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to})\nAND \"client_id\" IN (${Receiver:sqlstring})\nGROUP BY 1, 3\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  TIME_EXTRACT(\\\"__time\\\",'hour') AS \\\"hour\\\",\\n  COUNT (DISTINCT \\\"hex_ident_val\\\") AS \\\"aircraft tracked\\\",\\n  \\\"client_id\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to})\\nAND \\\"client_id\\\" IN (${Receiver:sqlstring})\\nGROUP BY 1, 3\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Percentile altitude by hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n  TIME_EXTRACT(\"__time\",'hour') AS \"hour\",\n  DS_GET_QUANTILE(DS_QUANTILES_SKETCH(\"altitude\"), 0.25) AS \"25percent\",\n  DS_GET_QUANTILE(DS_QUANTILES_SKETCH(\"altitude\"), 0.5) AS \"50percent\",\n  DS_GET_QUANTILE(DS_QUANTILES_SKETCH(\"altitude\"), 0.75) AS \"75percent\"\nFROM \"adsb-json\"\nWHERE  \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to})\nAND \"client_id\" IN (${Receiver:sqlstring})\nGROUP BY 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  TIME_EXTRACT(\\\"__time\\\",'hour') AS \\\"hour\\\",\\n  DS_GET_QUANTILE(DS_QUANTILES_SKETCH(\\\"altitude\\\"), 0.25) AS \\\"25percent\\\",\\n  DS_GET_QUANTILE(DS_QUANTILES_SKETCH(\\\"altitude\\\"), 0.5) AS \\\"50percent\\\",\\n  DS_GET_QUANTILE(DS_QUANTILES_SKETCH(\\\"altitude\\\"), 0.75) AS \\\"75percent\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE  \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to})\\nAND \\\"client_id\\\" IN (${Receiver:sqlstring})\\nGROUP BY 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}