{
 "title": "Flight Data",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Receiver",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Tracked Aircraft",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"hex_ident_val\", \"client_id\",\nAVG(\"latitude\") as \"latitude\",\nAVG(\"longitude\") as \"longitude\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"latitude\" IS NOT NULL AND \"longitude\" IS NOT NULL AND \"client_id\" IN (${Receiver:sqlstring})\nGROUP BY 1, 2\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"hex_ident_val\\\", \\\"client_id\\\",\\nAVG(\\\"latitude\\\") as \\\"latitude\\\",\\nAVG(\\\"longitude\\\") as \\\"longitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"latitude\\\" IS NOT NULL AND \\\"longitude\\\" IS NOT NULL AND \\\"client_id\\\" IN (${Receiver:sqlstring})\\nGROUP BY 1, 2\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"client_id\", \nAVG(\"client_lat\") as \"latitude\",\nAVG(\"client_lon\") as \"longitude\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"latitude\" IS NOT NULL AND \"longitude\" IS NOT NULL AND \"client_id\" IN (${Receiver:sqlstring})\nGROUP BY 1\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"client_id\\\", \\nAVG(\\\"client_lat\\\") as \\\"latitude\\\",\\nAVG(\\\"client_lon\\\") as \\\"longitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"latitude\\\" IS NOT NULL AND \\\"longitude\\\" IS NOT NULL AND \\\"client_id\\\" IN (${Receiver:sqlstring})\\nGROUP BY 1\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Total Unique Aircraft by Receiver",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n  \"client_id\" AS \"receiver\",\n  COUNT (DISTINCT \"hex_ident_val\") AS \"aircraft tracked\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"client_id\" IN (${Receiver:sqlstring})\nGROUP BY 1\nORDER BY 2 DESC",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  \\\"client_id\\\" AS \\\"receiver\\\",\\n  COUNT (DISTINCT \\\"hex_ident_val\\\") AS \\\"aircraft tracked\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"client_id\\\" IN (${Receiver:sqlstring})\\nGROUP BY 1\\nORDER BY 2 DESC\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Average Horizontal Distance to Aircraft",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n  \"client_id\" AS \"receiver\",\n  AVG(\"distance_to_aircraft\")\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"client_id\" IN (${Receiver:sqlstring})\nGROUP BY 1 ORDER BY 2",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  \\\"client_id\\\" AS \\\"receiver\\\",\\n  AVG(\\\"distance_to_aircraft\\\")\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"client_id\\\" IN (${Receiver:sqlstring})\\nGROUP BY 1 ORDER BY 2\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Shortest Horizontal Distance to Aircraft",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n  \"client_id\" AS \"receiver\",\n  MIN(CAST(\"distance_to_aircraft\" AS DOUBLE))\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"client_id\" IN (${Receiver:sqlstring})\nGROUP BY 1 ORDER BY 2",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  \\\"client_id\\\" AS \\\"receiver\\\",\\n  MIN(CAST(\\\"distance_to_aircraft\\\" AS DOUBLE))\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"client_id\\\" IN (${Receiver:sqlstring})\\nGROUP BY 1 ORDER BY 2\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}