{
 "title": "Individual Flight View",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Aircraft",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Aircraft Route",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"latitude\", \"longitude\"\nFROM \"adsb-json\"\nWHERE \"hex_ident_val\" IN (${Aircraft:sqlstring})\nAND \"latitude\" IS NOT NULL\nAND \"longitude\" IS NOT NULL\nORDER BY \"__time\" DESC\nLIMIT 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"latitude\\\", \\\"longitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"hex_ident_val\\\" IN (${Aircraft:sqlstring})\\nAND \\\"latitude\\\" IS NOT NULL\\nAND \\\"longitude\\\" IS NOT NULL\\nORDER BY \\\"__time\\\" DESC\\nLIMIT 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"track\"\nFROM \"adsb-json\"\nWHERE \"hex_ident_val\" IN (${Aircraft:sqlstring})\nAND \"track\" IS NOT NULL\nORDER BY \"__time\" DESC\nLIMIT 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"track\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"hex_ident_val\\\" IN (${Aircraft:sqlstring})\\nAND \\\"track\\\" IS NOT NULL\\nORDER BY \\\"__time\\\" DESC\\nLIMIT 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"latitude\", \"longitude\"\nFROM \"adsb-json\"\nWHERE \"hex_ident_val\" IN (${Aircraft:sqlstring})\nAND \"latitude\" IS NOT NULL\nAND \"longitude\" IS NOT NULL\nORDER BY \"__time\" DESC\nLIMIT 10",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"latitude\\\", \\\"longitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"hex_ident_val\\\" IN (${Aircraft:sqlstring})\\nAND \\\"latitude\\\" IS NOT NULL\\nAND \\\"longitude\\\" IS NOT NULL\\nORDER BY \\\"__time\\\" DESC\\nLIMIT 10\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"altitude\"\nFROM \"adsb-json\"\nWHERE \"hex_ident_val\" IN (${Aircraft:sqlstring})\nAND \"altitude\" IS NOT NULL\nORDER BY \"__time\" DESC\nLIMIT 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"altitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"hex_ident_val\\\" IN (${Aircraft:sqlstring})\\nAND \\\"altitude\\\" IS NOT NULL\\nORDER BY \\\"__time\\\" DESC\\nLIMIT 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Ground Speed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n  \"ground_speed\"\nFROM \"adsb-json\" WHERE \"ground_speed\" IS NOT NULL AND \"hex_ident_val\" IN (${Aircraft:sqlstring}) ORDER BY \"__time\" DESC LIMIT 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  \\\"ground_speed\\\"\\nFROM \\\"adsb-json\\\" WHERE \\\"ground_speed\\\" IS NOT NULL AND \\\"hex_ident_val\\\" IN (${Aircraft:sqlstring}) ORDER BY \\\"__time\\\" DESC LIMIT 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Heading",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"track\"\nFROM \"adsb-json\"\nWHERE \"hex_ident_val\" IN (${Aircraft:sqlstring})\nAND \"track\" IS NOT NULL\nORDER BY \"__time\" DESC\nLIMIT 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"track\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"hex_ident_val\\\" IN (${Aircraft:sqlstring})\\nAND \\\"track\\\" IS NOT NULL\\nORDER BY \\\"__time\\\" DESC\\nLIMIT 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Flight Details",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"squawk\", \"client_id\"\nFROM \"adsb-json\"\nWHERE \"hex_ident_val\" IN (${Aircraft:sqlstring})\nAND \"squawk\" IS NOT NULL\nORDER BY \"__time\" DESC\nLIMIT 1",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"squawk\\\", \\\"client_id\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"hex_ident_val\\\" IN (${Aircraft:sqlstring})\\nAND \\\"squawk\\\" IS NOT NULL\\nORDER BY \\\"__time\\\" DESC\\nLIMIT 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}